apiVersion: apps/v1
kind: Deployment
metadata:
  name: result
spec:
  replicas: 1
  selector:
    matchLabels:
      app: result
  template:
    metadata:
      labels:
        app: result
    spec:
      containers:
        - name: result
          image: 681885730059.dkr.ecr.us-east-1.amazonaws.com/voting-app/result:b180fa05da481663eb4c44773f50b3ff0ecd9dc2
          ports:
            - containerPort: 80