apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote
spec:
  replicas: 1   # kept at 1, not 2, due to t3.micro's constrained memory — see note above
  selector:
    matchLabels:
      app: vote
  template:
    metadata:
      labels:
        app: vote
    spec:
      containers:
        - name: vote
          image: 681885730059.dkr.ecr.us-east-1.amazonaws.com/voting-app/vote:b180fa05da481663eb4c44773f50b3ff0ecd9dc2
          ports:
            - containerPort: 80