apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - name: worker
          image: 681885730059.dkr.ecr.us-east-1.amazonaws.com/voting-app/worker:b180fa05da481663eb4c44773f50b3ff0ecd9dc2