name: DAST Scan

on:
  workflow_dispatch:

permissions:
  contents: read
  issues: write

jobs:
  zap-scan:
    runs-on: ubuntu-latest
    steps:
      - name: ZAP Baseline Scan
        uses: zaproxy/action-baseline@906a3c93ffde4864839d31a93daadcbd2737b4da # v0.12.0
        with:
          # Hardcoded load balancer URL for the vote service.
          # If it changes, get the current one with:
          #   kubectl get svc vote -o jsonpath='{.status.loadBalancer.ingress[0].hostname}'
          target:  'http://a3201253b2a414e379b72fae5118e4ca-1707207753.us-east-1.elb.amazonaws.com'
          